### ISSUE TITLE
Конкуренты

### ISSUE THREAD

**Issue by knowmaker** [Kernazhytski/StuQuesProject#85]
В чем заключается отличие от аналогичных сайтов в сети интернет?

**Comment by Kernazhytski** [comment]
Наш сайт - это совмещение двух знаменитых проектов, таких как Stackoverflow и Znaniya. У нас реализована продвинутая авторизация и кастомизация профиля. Так же был сделан дружественный UI, что позволяет удобно работать с сайтом как на ПК, так и с телефона. Но главная особенность нашего проекта - это его открытость. Все знаменитые аналоги не имеют Open Source кода. Наш проект может помочь не только ответить на вопросы, заданные на сайте, но так же и передать опыт в разработке подобных сайтов и реализации наших механик.

**Comment by Kernazhytski** [comment]
Ответили на вопрос
